### ISSUE TITLE
Make database

### ISSUE THREAD

**Issue by bradenrayhorn** [bradenrayhorn/hospitalapp#1]

**Comment by Scamper101** [comment]
Ok, so there are some things we need to talk about in regards to the database. For the messages table, the template says to use the doctorID as a foreign key for the MessageFROM field; this would mean only doctors would be able to send messages. Not sure if we want to keep it this way or what. 

Another problem I ran into was using the script to generate the database. In the PatientsTable, the foreign keys for MedicationID and TestID are required. However, the MedicationTable and TestTable both require PatientID as a foreign key; basically, you cant create one table without the other already existing. I'm not really sure how to get around this.

**Comment by bradenrayhorn** [comment]
@Scamper101 I think the MessageFrom and MessageTo field should both be `UserLoginName`, the requirements mention that both patients and doctors should be able to send messages. 

As for the PatientsTable, I'd just remove the foreign key constraint for the MedicationID and TestID fields. I still don't think they make much sense there but she said we should leave them so we can leave them there without the foreign key. Then you can keep the foreign key constraint on the MedicationTable and TestTable.

**Comment by bradenrayhorn** [comment]
ef0d772dd8f484da011a524c8721b5e4896ff21d
